### ISSUE TITLE
Store UI cannot fetch products list from API

### ISSUE THREAD

**Issue by evanshortiss** [redhat-scholars/cloud-native-apps#3]
The Angular UI forces the use of HTTPS/HTTP to fetch products based on the location it's being served from. You can confirm this in the [code here](https://github.com/modernizing-java-applications-book/web-nodejs/blob/main/app/services/catalog.js#L8-L12). 

The deployed gateway Route is using HTTP, but since the Node.js instructions use S2I and default Route configuration it uses HTTPS. This means when the UI tries to fetch the products it fails, since the UI code forces the use of HTTPS.

Possible solutions:

1. Change the UI code to respect the protocol defined in the environment variable
2. Modify the Vertx application YAML to use a HTTPS Route
3. Update the instructions to disable HTTPS for the UI, or enable it on the Vertx service

Edit: The JS code also only observes the route name, as opposed to the fully qualified URL, so the instructions need to mention this too, or the JS could be updated to handle this scenario.

<img width="1507" alt="Screenshot 2022-09-07 at 5 05 54 PM" src="https://user-images.githubusercontent.com/1303687/189005774-f255afdf-743f-44ee-a4ed-d17ae19ed4db.png">

**Comment by hpgrahsl** [comment]
During my re-run of the whole thing for making a couple of other improvements I tried to fix the route in the YAML as you suggest as solution option 2). Worked fine for me in the end and I think it's an easy fix and also consistent with everything else being https in the lab so we could go for this IMHO. So the following spec (I added the tls section on the fly) would work:

```yaml
spec:
  host: [...]
  to:
    kind: Service
    name: gateway-vertx
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
```
